[package]
name = "app_config"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.15.11"
dotenvy = "0.15.7"
serde = { version = "1.0.215", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[dev-dependencies]
serial_test = "3.2.0"
temp-env = "0.3.6"
tempfile = "3.14.0"
