[workspace]
members = ["app_config", "db", "scraper", "scraper_utils", "server"]

[package]
name = "share_service"
version = "0.1.0"
edition = "2021"

[dependencies]
app_config = { path = "app_config" }
db = { path = "db" }
scraper_utils = { path = "scraper_utils" }
indicatif = { version = "0.18.4", features = ["in_memory"] }
tabled = "0.20.0"
tokio = { version = "1.42.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[dev-dependencies]
chrono = "0.4.39"
scraper = { path = "scraper" }
