[package]
name = "scraper_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
db = { path = "../db/" }
scraper = { path = "../scraper/" }
tracing = "0.1.41"
chrono = { version = "0.4.38", features = ["serde"] }
